### ISSUE TITLE
Bitbucket flavor markdown

### ISSUE THREAD

**Issue by atilacamurca** [g4code/changelogger#2]
I'm planning to submit a PR with the option output to be Bitbucket flavor markdown, what you guys suggest to be the format option?

* [ ] bbfm (**B**it**b**ucket **F**lavor **M**arkdown)
* [x] bbmd (**B**it**b**ucket  **M**ark**d**own)
* [ ] bitbucket-md

Just so you know I think the only difference from the current markdown option is the ability to put anchor links. Bitbucket uses a prefix `markdown-header-` and replace some characters in the string such as space, latin accents; and only lowercase characters.

**Comment by gomboc** [comment]
bbmd sounds ok to me
